### ISSUE TITLE
Create a generic crawler that take a projects.yaml file as input

### ISSUE THREAD

**Issue by morucci** [morucci/monocle#15]
Idea is to have one crawler process able to handle a list of project definition whatever project is hosted on Gerrit or Github.

Format could be as:

```YAML
- projects:
   - name: my-project
     crawler:
         gerrit_repositories:
            - name: ^softwarefactory/.*
              updated_since: 2020-01-01
              loop_delay: 300
            - name: ^rpms/.*
              updated_since: 2020-01-01
              loop_delay: 300         
   - name: m-project-2
     crawler:
        github_orgs:
           - name: org1
             updated_since: 2020-01-01
             loop_delay: 300
           - name: org2
             updated_since: 2020-01-01
             loop_delay: 300       
```
